apiVersion: v1
kind: Config
clusters:
- name: "cluster-swe"
  cluster:
    server: "https://18.209.26.76/k8s/clusters/c-ff5k8"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0TURjMApOak00TXpBZUZ3MHlNekEwTURZd01UVTVORE5hRncwek16QTBNRE13TVRVNU5ETmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZ3dOelEyTXpnek1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXExUFlwK1lIZ1VxQwpJME5uMlV5N3E2ZENsZ3VqUW5pQWdnaEIyW\
      TlZRXpHcE0vbldBU0ZWT2drTUp2MFpRSUd6dVNMOThOTHJuWWhaCnVHT1ZWVUJsVmFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      kcrKzRSV25VMktFdGdNVWRsWUZZNEF6Vzk4TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUcvUgpvT\
      jNXTGYxUDViT0d5KzFyZG9oZ2lmUEY1UEhVeUlXOUNucVdPOXVaQWlFQXI1Uml3TU1SZzg2TnJFN\
      GV3QmZYClBIMUtCbForUGlFM2Z4ZUJ4VEtWcXJnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "cluster-swe"
  user:
    token: "kubeconfig-user-wjpffz4sfk:dhnswgtq8n6v6b2vb7kmdxwgxxlh9jlfv24f7zm9684nnrl4qqsfbs"


contexts:
- name: "cluster-swe"
  context:
    user: "cluster-swe"
    cluster: "cluster-swe"

current-context: "cluster-swe"
